[package]
name = "tideapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scmodel = { path = "../scmodel" }
tide = "0.14.0"
femme = "2.2.1"
async-std = { version = "1.6.0", features = ["attributes"] }
serde = {version = "1.0.160", features = ["derive"]}
serde_json = "1.0.103"

